4.14
ALTER TABLE `CodeU_2017DB`.`User` 
ADD COLUMN `salt` VARCHAR(45) NOT NULL AFTER `password`;

4.15
ALTER TABLE `CodeU_2017DB`.`User`
CHANGE COLUMN `username` `username` VARCHAR(60) NOT NULL,
CHANGE COLUMN `Uuid` `Uuid` VARCHAR(60) NOT NULL ,
CHANGE COLUMN `password` `password` VARCHAR(64) NOT NULL ,
CHANGE COLUMN `salt` `salt` VARCHAR(60) NOT NULL;